### ISSUE TITLE
checkmk agent 2.2.0p12 is not updated

### ISSUE THREAD

**Issue by danfate** [Donimax/unraid-check-mk-agent#20]
Hello,
I think this compare logic in workflow file may cause the bug that when old version is 9 and newer is 11

<img width="449" alt="image" src="https://github.com/Donimax/unraid-check-mk-agent/assets/8059612/df12545d-7ef2-4391-9494-b65b28ac0754">

**Comment by Donimax** [comment]
I will take a look, thx
