### ISSUE TITLE
Agent refuses connection from checkmk server

### ISSUE THREAD

**Issue by servebeer** [Donimax/unraid-check-mk-agent#62]
I setup the script with the appropriate settings. I then ran it one time and I did not notice any errors. When I try to add my unraid server to checkmk and run a service discovery, I get: "CRIT [agent]: No cached data available CRIT" or "CRIT [agent]: Communication failed: [Errno 111] Connection refused CRIT" There is no authentication or encryption setup between the server and agents, so I am not sure why the agent keeps refusing the connection?

Jon

**Comment by Donimax** [comment]
Hi @servebeer Jon,
What version have you installed?
Do you get a reply when you telnet to your unraid server on port 6556: `telnet 192.168.1.xxx 6556`?
If not, check that xinetd is running: `ps auxf | grep xinetd`.

Please also check if the file ckech_mk is present in `/etc/xinetd.d/check_mk'.
and the binary in `/usr/bin/check_mk_agent`.

The last step is to run the binary and check if you see any output.

Max

**Comment by Donimax** [comment]
Hi @servebeer any update from your side?

**Comment by Donimax** [comment]
If you have any updates, you can re-open this issue
