### ISSUE TITLE
Monitor SMART  values of the Harddrives 

### ISSUE THREAD

**Issue by lubeda** [Donimax/unraid-check-mk-agent#65]
Hi, i'm using a Terramaster F4-423 as unraid host. The plugin doesn't monitor the smart values of the host. Would this be possible? What do i have to configure for this feature?

Greetings

**Comment by Donimax** [comment]
Hi @lubeda 
please follow this documentation in my README:
https://github.com/Donimax/unraid-check-mk-agent?tab=readme-ov-file#checkmk-docker-and-smart-plugin

With this you can monitor your docker and smart on Unraid.

**Comment by lubeda** [comment]
Sorry, i didn't read the manual. This works fine! But i had to change the url to **http**. 

Danke, cooles AddOn!!!
