### ISSUE TITLE
More of a quesiton then a issue

### ISSUE THREAD

**Issue by bmartino1** [Donimax/unraid-check-mk-agent#74]
![image](https://github.com/user-attachments/assets/8660673e-5ca1-4988-a247-932ce8882571)

in unraid i see there are multiple agents. Is there a reason for the older version?

**Comment by Donimax** [comment]
Hi @bmartino1,
The older version is retained because not everyone upgrades to the latest server release for various reasons, such as deprecations and other factors. CheckMk continues to support the older version by offering fixes and security updates.

**Comment by Donimax** [comment]
@bmartino1 Do you have any questions? If not, I will close this issue.

**Comment by bmartino1** [comment]
This can be closed. Thanks
